name: CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js for use with actions
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '10.16'

    - name: npm instatll
      run:  yarn

    - name: clean cache
      run: yarn cache clean
    - name: Lint
      run: yarn lint

